version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  secret:
    image: s888db
    ports:
      - '10000:10000'
    command:
      - "server"
      - "-x=postgresql://postgres:mypassword@db:5432/secret_db?sslmode=disable"
      - "-o=10000"
